### ISSUE TITLE
Documentation page not found

### ISSUE THREAD

**Issue by turpaultn** [CPJKU/audio-tagger#1]
Hi, 
I'm interested in this work.
However the [documentation link](https://github.com/CPJKU/audio-tagger/blob/master/docs/html) is broken (404 page not found)
Best,

**Comment by fhenkel** [comment]
Hi,

this was more intended as an offline documentation. If you clone the project and open "audio-tagger/docs/_build/html/index.html" with your browser you will be able to access it.
